repos:
  # Versioning: Commit messages & changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.13.0
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Autoformat: Python code
  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black

  # Lint / autoformat: Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.1.7"
    hooks:
      - id: ruff
        args: [--exit-non-zero-on-fix]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.4
    hooks:
      - id: prettier
        args:
          [
            --ignore-unknown,
            --no-error-on-unmatched-pattern,
            "!chart/**",
            "!CHANGELOG.md",
            "!tests/testdata/*",
          ]
  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.38.0
    hooks:
      - id: markdownlint
        args: [--fix, --ignore, CHANGELOG.md, --ignore, LICENSE.md]
