repos:
  # Versioning: Commit messages & changelog
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.1.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  # Lint / autoformat: Python code
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: "v0.9.3"
    hooks:
      # Run the linter
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
      # Run the formatter
      - id: ruff-format

  # Lint & Autoformat: SQL
  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 3.3.0
    hooks:
      - id: sqlfluff-lint
        files: ^fmtm_splitter/fmtm_algorithm.sql
        # files: ^fmtm_splitter/.*\.sql$
        types: [sql]
      - id: sqlfluff-fix
        files: ^fmtm_splitter/fmtm_algorithm.sql
        # files: ^fmtm_splitter/.*\.sql$
        types: [sql]

  # Autoformat: YAML, JSON, Markdown, etc.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        entry: env PRETTIER_LEGACY_CLI=1 prettier
        args:
          [
            --ignore-unknown,
            --no-error-on-unmatched-pattern,
            "!fmtm-splitter/fmtm-splitter_osm_buildings/**",
            "!contrib/postgis_snippets/**",
            "!CHANGELOG.md",
            "!tests/testdata/*",
          ]
  # Lint: Markdown
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.44.0
    hooks:
      - id: markdownlint
        args:
          [
            --fix,
            --ignore,
            CHANGELOG.md,
            --ignore,
            contrib/postgis_snippets/**/*.md,
            --ignore,
            fmtm_splitter/fmtm-splitter_osm_buildings/*.md,
          ]
