name: 🧪 PyTest

on:
  push:
    branches: [main]
  # Run tests on PR, prior to merge to main & development
  pull_request:
    branches: [main]
  # Allow manual trigger (workflow_dispatch)
  workflow_dispatch:

jobs:
  pytest:
    uses: hotosm/gh-workflows/.github/workflows/test_compose.yml@1.4.3
    with:
      image_name: ghcr.io/${{ github.repository }}
      tag_override: ci
      compose_file: compose.yml
      compose_service: splitter
      compose_command: pytest
      cache_extra_imgs: |
        "docker.io/postgis/postgis:14-3.4-alpine"
